### ISSUE TITLE
Create a structure for the 'title.ratings' data

### ISSUE THREAD

**Issue by Maksym637** [Maksym637/big-data-project#10]
1. In the `models.py` file, fill in the appropriate column names
2. In the `schemas.py` file, create the appropriate schemas (pay attention to data types)
3. In the `jobs` folder, create a `{data}_job.py` file, within which create a data-specific class
4. Come up with 3 - 6 different business questions
5. Implement them as methods of the class
6. Check your program execution in the `main.py` class

**Comment by EyR1oN** [comment]
Okay

**Comment by Maksym637** [comment]
Business questions:

1. Count how many titles have a rating above a certain threshold
2. Count titles with less than a certain number of votes
3. Calculate the average number of votes per rating interval
4. Calculate the running total of votes and the average rating for each title, ordered by average rating in descending order
5. Identify the highest average rating within each group of 5 titles, sorted by number of votes in descending order
6. Find the average rating of movies directed by a specific director

**Comment by Maksym637** [comment]
Please think up **2** questions with the following functions:

- join
- window function

**Comment by Maksym637** [comment]
Done
