### ISSUE TITLE
Create a structure for the 'title.akas' data

### ISSUE THREAD

**Issue by Maksym637** [Maksym637/big-data-project#5]
1. In the `models.py` file, fill in the appropriate column names
2. In the `schemas.py` file, create the appropriate schemas (pay attention to data types)
3. In the `jobs` folder, create a `{data}_job.py` file, within which create a data-specific class
4. Come up with 3 - 6 different business questions
5. Implement them as methods of the class
6. Check your program execution in the `main.py` class

**Comment by m-gorg** [comment]
Business questions:

1. Count titles with Ukrainian localization
2. Get unique languages
3. Get the number of titles for each title type
4. Get pairs [original title - bowdlerized title] for all bowdlerized titles
5. Rank titles by localization count
6. Rank regions by count of DVD titles

**Comment by Maksym637** [comment]
Done
