### ISSUE TITLE
Create a structure for the 'title.crew' data

### ISSUE THREAD

**Issue by Maksym637** [Maksym637/big-data-project#7]
1. In the `models.py` file, fill in the appropriate column names
2. In the `schemas.py` file, create the appropriate schemas (pay attention to data types)
3. In the `jobs` folder, create a `{data}_job.py` file, within which create a data-specific class
4. Come up with 3 - 6 different business questions
5. Implement them as methods of the class
6. Check your program execution in the `main.py` class

**Comment by augusto-alexus** [comment]
Business questions:
1. Get all titles without writers in their crew.
2. Get top 10 titles with the most crew members (directors + writers, count unique only).
3. Get titles where only one person worked both as director and writer.
4. Get titles where director also played one of the characters.
5. Rank titles for each writer worked on based on their average rating.
6. Get the number of titles each director has worked on.

**Comment by augusto-alexus** [comment]
PR #16

**Comment by Maksym637** [comment]
Done
